platform :ios, '15.5'

source 'https://github.com/iwater/google-mlkit-ios-arm64-simulator-specs.git'
source 'https://cdn.cocoapods.org/'

target 'ocrexample' do
  use_frameworks! :linkage => :static

  pod 'MLKitCommon',                '~> 14.0.0'
  pod 'MLKitVision',                '~> 10.0.0'
  pod 'MLKitTextRecognitionCommon', '~> 6.0.0'
  pod 'MLKitTextRecognition',       '~> 7.0.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
    end
  end

end
